INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Pano de prato', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Porta guardanapo', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Açucareiro', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Jogo americano', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Prato', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Descanso de panela', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Mesa', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Cadeira', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Xícara', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Copo', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Caneca', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Toalha de Mesa', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Bandeja', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de jantar', 'Talheres', '0');

INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de estar', 'Televisão', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de estar', 'Mesa de canto', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de estar', 'Sofá', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de estar', 'Painel', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de estar', 'Tapete', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Sala de estar', 'Cortina', '0');

INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Cama', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Colchão', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Guarda roupa', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Mesas de apoio', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Sapateira', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Cortina', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Prateleira', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Abajur', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Cabide', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Cobertor', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Lençol', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Travesseiro', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Penteadeira', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Quarto', 'Tapete', '0');

INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Mesa de trabalho', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Cadeira', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Prateleira', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Livros', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Estante', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Computador', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Impressora', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Mural', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Poltrona', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Lixeira', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Tapete', '0');
INSERT INTO HENX (COM, ITE, TEM) VALUES ('Escritório', 'Cortina', '0');